# Base configuration that contains common settings
base_config:
  base_results_dir: "/home/goring/TF_spectrum/results/biggrid_1703_bug"
  epochs: 5000
  batch_size: 65536 
  checkpoint_epochs: []
  weight_decay: 0
  n_test: 20000
  save_model: false
  normalize_data: false
  num_experiments: 1
  restart_checkpoint: null

# Sweeps with their specific dataset paths
sweeps:
  # Learning rate sweep for first dataset group
  sweep_full:
    dataset_paths:
      - "/home/goring/TF_spectrum/pretrain/grid_1703_bug/PT_NP_d8_H2_D2_a0.0_O_1_20250317_183459"
      -  "/home/goring/TF_spectrum/pretrain/grid_1703_bug/PT_NP_d8_H2_D2_a0.5_O_1_20250317_183820"
      -  "/home/goring/TF_spectrum/pretrain/grid_1703_bug/PT_NP_d8_H2_D2_a1.0_O_1_20250317_184134"
      -  "/home/goring/TF_spectrum/pretrain/grid_1703_bug/PT_NP_d8_H2_D2_a4.0_O_1_20250317_183547"
      -  "/home/goring/TF_spectrum/pretrain/grid_1703_bug/PT_NP_d8_H2_D2_a8.0_O_1_20250317_184356"
      -  "/home/goring/TF_spectrum/pretrain/grid_1703_bug/PT_NP_d8_H4_D2_a0.0_O_1_20250317_183546"
      -  "/home/goring/TF_spectrum/pretrain/grid_1703_bug/PT_NP_d8_H4_D2_a0.5_O_1_20250317_183907"
      -  "/home/goring/TF_spectrum/pretrain/grid_1703_bug/PT_NP_d8_H4_D2_a1.0_O_1_20250317_184220"
      -  "/home/goring/TF_spectrum/pretrain/grid_1703_bug/PT_NP_d8_H4_D2_a4.0_O_1_20250317_183748"
      -  "/home/goring/TF_spectrum/pretrain/grid_1703_bug/PT_NP_d8_H4_D2_a8.0_O_1_20250317_184537"
      -  "/home/goring/TF_spectrum/pretrain/grid_1703_bug/PT_NP_d8_H8_D2_a0.0_O_1_20250317_183631"
      -  "/home/goring/TF_spectrum/pretrain/grid_1703_bug/PT_NP_d8_H8_D2_a0.5_O_1_20250317_183952"
      -  "/home/goring/TF_spectrum/pretrain/grid_1703_bug/PT_NP_d8_H8_D2_a1.0_O_1_20250317_184306"
      -  "/home/goring/TF_spectrum/pretrain/grid_1703_bug/PT_NP_d8_H8_D2_a4.0_O_1_20250317_183944"
      -  "/home/goring/TF_spectrum/pretrain/grid_1703_bug/PT_NP_d8_H8_D2_a8.0_O_1_20250317_184740"
      -  "/home/goring/TF_spectrum/pretrain/grid_1703_bug/PT_NP_d8_H16_D2_a0.0_O_1_20250317_183731"
      -  "/home/goring/TF_spectrum/pretrain/grid_1703_bug/PT_NP_d8_H16_D2_a0.5_O_1_20250317_184049"
      -  "/home/goring/TF_spectrum/pretrain/grid_1703_bug/PT_NP_d8_H16_D2_a1.0_O_1_20250317_184403"
      -  "/home/goring/TF_spectrum/pretrain/grid_1703_bug/PT_NP_d8_H16_D2_a4.0_O_1_20250317_184204"
      -  "/home/goring/TF_spectrum/pretrain/grid_1703_bug/PT_NP_d8_H16_D2_a8.0_O_1_20250317_185009"
      -  "/home/goring/TF_spectrum/pretrain/grid_1703_bug/PT_NP_d8_H32_D2_a0.0_O_1_20250317_183559"
      -  "/home/goring/TF_spectrum/pretrain/grid_1703_bug/PT_NP_d8_H32_D2_a0.5_O_1_20250317_184708"
      -  "/home/goring/TF_spectrum/pretrain/grid_1703_bug/PT_NP_d8_H32_D2_a1.0_O_1_20250317_185823"
      -  "/home/goring/TF_spectrum/pretrain/grid_1703_bug/PT_NP_d8_H32_D2_a4.0_O_1_20250317_183520"
      -  "/home/goring/TF_spectrum/pretrain/grid_1703_bug/PT_NP_d8_H32_D2_a8.0_O_1_20250317_184706"
      -  "/home/goring/TF_spectrum/pretrain/grid_1703_bug/PT_NP_d8_H64_D2_a0.0_O_1_20250317_183849"
      -  "/home/goring/TF_spectrum/pretrain/grid_1703_bug/PT_NP_d8_H64_D2_a0.5_O_1_20250317_184956"
      -  "/home/goring/TF_spectrum/pretrain/grid_1703_bug/PT_NP_d8_H64_D2_a1.0_O_1_20250317_190111"
      -  "/home/goring/TF_spectrum/pretrain/grid_1703_bug/PT_NP_d8_H64_D2_a4.0_O_1_20250317_183814"
      -  "/home/goring/TF_spectrum/pretrain/grid_1703_bug/PT_NP_d8_H64_D2_a8.0_O_1_20250317_184955"
      - "/home/goring/TF_spectrum/pretrain/grid_1703_bug/PT_NP_d8_H128_D2_a0.0_O_1_20250317_184529"
      - "/home/goring/TF_spectrum/pretrain/grid_1703_bug/PT_NP_d8_H128_D2_a0.5_O_1_20250317_185647"
      - "/home/goring/TF_spectrum/pretrain/grid_1703_bug/PT_NP_d8_H128_D2_a1.0_O_1_20250317_190812"
      - "/home/goring/TF_spectrum/pretrain/grid_1703_bug/PT_NP_d8_H128_D2_a4.0_O_1_20250317_184528"
      - "/home/goring/TF_spectrum/pretrain/grid_1703_bug/PT_NP_d8_H128_D2_a8.0_O_1_20250317_185756"
                  
      

    parameters:
      hidden_sizes: [256]  # Width parameter
      depths: [2]  # Depth parameter
      base_width: 256   # Base width parameter
      learning_rates: [0.001,0.005,0.0005] #0.0005,0.0001,0.00005,
      n_train: [10,100,1000,10000,50000,100000,200000,300000,500000,750000,1000000,2000000,3000000,45000000]
      modes: ["standard_lr"]
      alignment: [False]
  